version: '3'
services:
    laravel:
        image: carpeng/php8-3_apache-agorakit
        command: ["php", "artisan", "serve" ,"--host=0.0.0.0"]
        environment:
            - CGROUP=1000
            - CNAME=1000
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80:8000'
            - '5173:5173'
        volumes:
            - '.:/var/www/html'
        networks:
            - agorakit
        depends_on:
            - mysql
    mysql:
        image: 'mysql'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'agorakit'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'root'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './.mysql:/var/lib/mysql'
        networks:
            - agorakit
networks:
    agorakit:
        driver: bridge
volumes:
    agorakit-mysql:
        driver: local